config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root "welcome#index"
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
                                  endpoint: 'https://sandbox.iexapis.com/v1')
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    Stock.where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
    stocks.count < 10
  end

  def tracking_stock?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !tracking_stock?(ticker_symbol)
  end

  def full_name
    first_name || last_name ? "#{first_name} #{last_name}" : "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_name_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_name_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_friend)
    !self.friends.ids.include?(id_friend)
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    current_user.friendships.where(friend_id: params[:id]).first.destroy
    flash[:notice] = "#{User.find(params[:id]).full_name} was deleted from your friendlist"
    redirect_to my_friends_path
  end

  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Following user"
    else
      flash[:alert] = "Something wrong with following request"
    end
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    @user = current_user
    if !params[:stock].empty?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        @tracked_stocks = current_user.stocks
        render 'users/my_portfolio'
      else
        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    UserStock.where(user_id: current_user.id, stock_id: stock.id).first.destroy
    flash[:notice] = "Stock #{stock.name} was successfully removed from your portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @followed_friends = current_user.friends
  end

  def search
    if !params[:friend].empty?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if !@friends.empty?
        @followed_friends = current_user.friends
        render 'users/my_friends'
      else
        flash[:alert] = "Couldn't find this user"
        redirect_to my_friends_path
      end
    else
      flash[:alert] = "Please enter a friend name or email to search"
      redirect_to my_friends_path
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "FinanceTracker", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "My Portfolio", my_portfolio_path, class: request.path == my_portfolio_path ? "nav-link active" : "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Friends", my_friends_path, class: request.path == my_friends_path ? "nav-link active" : "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= fa_icon 'user' %> <%= current_user.full_name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon 'edit' %> Edit profile
              <% end %>
            </ul>
          </li>
          <li class="nav-item">
            <%= button_to("Logout", destroy_user_session_path, class: "btn btn-danger logout-button", method: :delete) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinanceTracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%#= javascript_importmap_tags %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>

<body>
<%= render 'layouts/navigation' %>
<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
</body>
</html>

app/views/stocks/_stock_table.html.erb
<div class="row mt-4">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td>
            <% if current_user.can_track_stock?(stock.ticker) %>
              <%= button_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-success btn-sm",form: {style: 'display:inline-block;'}, method: :post %>
            <% elsif current_user.id != @user.id %>
              <span class="badge bg-secondary badge-tracked">
                You are already tracking
                <% if !current_user.under_stock_limit? %>
                  10 stocks
                <% else %>
                  this stock
                <% end %>
              </span>
            <% end %>
            <% if current_user.id == @user.id %>
              <%= button_to "Remove", user_stock_path(stock), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-sm btn-warning", form: {style: 'display:inline-block;'} %>
            <% end %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<% if @friends %>
  <div class="card card-header results-block mt-4">
    <table class="col-md-12">
      <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td><strong>Name: </strong> <%= friend.full_name %></td>
          <td><strong>Email: </strong> <%= friend.email %></td>
          <td><strong>Actions: </strong> <%= link_to 'View Profile', user_path(friend), class: "btn btn-success btn-sm" %>
            <% if current_user.not_friends_with?(friend.id) %>
              <%= button_to 'Follow', friendships_path(friend: friend), class: "btn btn-success btn-sm", form: {style: 'display:inline-block;'}, method: :post %>
            <% else %>
            <span class="badge bg-secondary">
              You are friends
            </span>
              </td>
            <% end %>
            </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friendlist.html.erb
<div class="row mt-4">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @followed_friends.each do |friend| %>
        <tr>
          <th scope="row"><%= friend.first_name %></th>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= link_to "View profile", user_path(friend), class: "btn btn-sm btn-success" %>
            <%= button_to "Stop following", friendship_path(friend), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-sm btn-warning", form: {style: 'display:inline-block;'} %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<%#= render 'layouts/messages' %>

<% if @stock %>
  <div class="card card-header results-block mt-4">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Company: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= button_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success btn-sm",form: {style: 'display:inline-block;'}, method: :post %>
    <% else %>
    <span class="badge bg-secondary badge-tracked">
      You are already tracking
      <% if !current_user.under_stock_limit? %>
        10 stocks
      <% else %>
        this stock
      <% end %>
    </span>
    <% end %>
  </div>
<% end %>

app/views/users/my_friends.html.erb
<h1>My Friends</h1>
<%= turbo_frame_tag :form do %>
  <div class="search-area">
    <h3>Search Friends</h3>
    <%= form_with url: "/search_friend", local: false, method: :get do |f| %>
      <div class="form-group row">
        <div class="col-sm-9 no-right-padding">
          <%= text_field_tag :friend, params[:friend], placeholder: "Search your friend", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-sm-3 no-left-padding">
          <%= button_tag type: :submit, class: "btn btn-success" do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render 'users/friend_result' %>
  <% if !@followed_friends.empty? %>
    <%= render "users/friendlist" %>
  <% end %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<%= turbo_frame_tag :form do %>
  <div class="search-area">
    <h3>Search Stocks</h3>
    <%= form_with url: "/search_stock", local: false, method: :get do |f| %>
      <div class="form-group row">
        <div class="col-sm-9 no-right-padding">
          <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-sm-3 no-left-padding">
          <%= button_tag type: :submit, class: "btn btn-success" do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render 'users/result' %>
  <% if !@tracked_stocks.empty? %>
    <%= render 'stocks/stock_table' %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header results-block mt-4">
  <table class="col-md-12">
    <tbody>
    <tr>
      <td><strong>First Name: </strong> <%= @user.first_name %></td>
      <td><strong>Last Name: </strong> <%= @user.last_name %></td>
      <td><strong>Email: </strong> <%= @user.email %></td>
      <td>
        <% if current_user.not_friends_with?(@user.id) %>
          <%= button_to 'Follow', friendships_path(friend: @user), class: "btn btn-success btn-sm", method: :post %>
        <% else %>
            <span class="badge bg-secondary">
              You are friends
            </span>
          </td>
        <% end %>
        </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/stock_table' %>
  <% else %>
  <p class="lead"> This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<h1 class="text-center mt-4">Welcome to the Finance Tracker app</h1>

<div class="text-center mt-4"><%= link_to 'Start tracking', my_portfolio_path, class: "btn btn-outline-primary" %></div>